export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const SESSION_REQUEST = 'SESSION_REQUEST'
export const SESSION_RESPONSE = 'SESSION_RESPONSE'
export const SESSION_ERROR = 'SESSION_ERROR'

export const SESSION_UPDATE_REQUEST = 'SESSION_UPDATE_REQUEST'
export const SESSION_UPDATE_RESPONSE = 'SESSION_UPDATE_RESPONSE'
export const SESSION_UPDATE_ERROR = 'SESSION_UPDATE_ERROR'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_RESPONSE = 'LOGOUT_RESPONSE'
export const LOGOUT_ERROR = 'LOGOUT_REQUEST'

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST'
export const REGISTRATION_RESPONSE = 'REGISTRATION_RESPONSE'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_RESPONSE = 'PROFILE_UPDATE_RESPONSE'
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR'

export const DEVICE_REGISTRATION_REQUEST = 'DEVICE_REGISTRATION_REQUEST'
export const DEVICE_REGISTRATION_RESPONSE = 'DEVICE_REGISTRATION_RESPONSE'
export const DEVICE_REGISTRATION_ERROR = 'DEVICE_REGISTRATION_ERROR'
