export const LOGIN_REQUEST = 'REQUEST_LOGIN'
export const LOGIN_RESPONSE = 'RESPONSE_LOGIN'
export const ERROR_LOGIN = 'LOGIN_ERROR'

export const SESSION_REQUEST = 'SESSION_REQUEST'
export const SESSION_RESPONSE = 'SESSION_RESPONSE'
export const SESSION_ERROR = 'SESSION_ERROR'
