export {default as validateEmail} from './validateEmail'
export {default as validatePresenceOfFields} from './validatePresenceOfFields'
export {default as validateIdentifier} from './validateIdentifier' 
export {default as validateMinLength} from './validateMinLength'
export {default as validateCoincidence} from './validateCoincidence'
export {default as combineValidators} from './combineValidators'
